[Easy Merge] Add Mapping to File Mapper
googleinterns/filesystem-in-appsscript pull request #72
Opened 2020-07-03 07:01 UTC by satviksr

2020-07-06 13:28 UTC, paneendra-google requested changes

2020-07-06 13:28 UTC, paneendra-google commented on FileSystem/FileMapperMocker.js
> -var FileMapper = USE_FILEMAPPER_MOCKER ? VBAFileMapperMocker : VBAFileMapper;
Prefer VBA over Vba

2020-07-06 13:28 UTC, paneendra-google commented on FileSystem/appsscript.json
> +}
add newline at EOF

2020-07-07 05:38 UTC, satviksr commented on FileSystem/FileMapperMocker.js
> -var FileMapper = USE_FILEMAPPER_MOCKER ? VBAFileMapperMocker : VBAFileMapper;
Fixed

2020-07-07 05:40 UTC, satviksr commented on FileSystem/appsscript.json
> +}
Fixed

2020-07-07 05:51 UTC, paneendra-google approved these changes

2020-07-07 11:59 UTC, monikadhok approved these changes

2020-07-07 11:59 UTC, merged